### PR TITLE
Sponsors page with carousels and links

### PR DESCRIPTION
**Pull request by csteamengine**
### Problem / Feature

Needed a sponsors page.
### Solution

I made a sponsors page with image carousels.
### What To Test

Make sure everything works, and potentially offer a solution to either: 
1) Slow down the transition speed, not the delay,
2) or make the scrolling continuous, or potentially manual(horizontal)

Here are some images:
screen shot 2015-09-22 at 10 52 07 pm
screen shot 2015-09-22 at 10 52 15 pm
### Reviewer

@CivBase @MichaelRupertDev 

FYI: @KrashLeviathan @csteamengine @regalcat

### CODE REVIEW

**Comment by KrashLeviathan** [comment]
Looks pretty cool! My only thought is that they might not like only one sponsor showing at a time from each group. Especially because the last sponsor in that group would always show last. Maybe we can make it so for each level, all the sponsors are in a row that continuously scrolls from right to left? Otherwise, you could also use the column / row setup provided with bootstrap and have each level of sponsorship as a grid. Just my two cents though...

**Comment by csteamengine** [comment]
Yeah that's what I mentioned in the pull request. I would prefer to have it continuously scrolling but I couldn't figure out how to do that so if someone knows how I have all the images with links to the website in a new tab set up. All they would have to do is implement that or change the design which shouldn't be too bad.

**Comment by KrashLeviathan** [comment]
True. We could go with this and if someone wants to update it later they can.

**Comment by csteamengine** [comment]
Cool! I feel actually helpful! Until it crashes the site lol

**Comment by csteamengine** [comment]
I would also like to make it so more than one image is on the screen at one time. Something like this link 
http://coolcarousels.frebsite.nl/c/23/ would be sweet! I tried to get that to work, but alas, I failed.

**Comment by CivBase** [comment]
My primary concern is similar.  Each sponsor gets equal space on the site, regardless of their donation level.

**Comment by KrashLeviathan** [comment]
I actually went to their shop and talked to them last night. Got a number of different questions answered. And they're cool with our design ideas, by the way. But yeah, for this section, they would rather see it in grid form.

**Pull request closed without merging**
